server:
  port: 9527
spring:
  application:
    name: microservicecloud-zuul-gateway
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true
zuul:
  routes:
    xishi.serviceId: xishiApp
    xishi.path: /xishi/**
    ignored-services: xishiapp #禁止用微服务名称访问数据
#  prefix: /guantong
#  ignored-services: "*"

#当前服务的简要信息
info:
  app.name: zuul-microcloud
  company.name: www.zuul.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
